services:
  postgresql:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    healthcheck:
      test: curl -s http://localhost:5432 >/dev/null; [[ $$? == 52 ]] && echo 0 || echo 1
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data/init.postgres.sql:/docker-entrypoint-initdb.d/init.sql
  simpleauth:
    image: crossedbot/simpleauth:latest
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    depends_on:
      - postgresql
    links:
      - postgresql
    ports:
      - "${PORT}:8080"
#volumes:
#  data:

